#!/usr/bin/env python3
"""Generate sql/seed_data.sql (INSERTs) from the JSON bundle in /data.

Run AFTER build_seed.py. Load order: schema.sql -> seed_data.sql in Supabase.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.normpath(os.path.join(HERE, "..", "data"))
OUT = os.path.normpath(os.path.join(HERE, "..", "sql", "seed_data.sql"))


def load(name):
    with open(os.path.join(DATA_DIR, name)) as f:
        return json.load(f)


def s(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    district = load("district.json")
    schools = load("schools.json")
    safety = load("safety.json")
    graduation = load("graduation.json")

    lines = [
        "-- Auto-generated by pipeline/build_sql_inserts.py. Do not edit by hand.",
        "-- Load order: schema.sql then this file.",
        "begin;",
        "",
    ]

    # District (Polygon -> MultiPolygon via ST_Multi)
    ring = ", ".join(f"{lon} {lat}" for lon, lat in district["geometry"]["coordinates"][0])
    lines.append(
        "insert into school_districts (district_id, name, short_name, state, geom) values\n"
        f"  ({s(district['districtId'])}, {s(district['name'])}, {s(district['shortName'])}, "
        f"{s(district['state'])}, ST_Multi(ST_GeomFromText('POLYGON(({ring}))', 4326)))\n"
        "on conflict (district_id) do nothing;\n"
    )

    # Schools
    lines.append("insert into schools (nces_id, name, type, grade_low, grade_high, zip, district_id, enrollment, student_teacher_ratio, geom) values")
    rows = []
    for sc in schools:
        rows.append(
            f"  ({s(sc['ncesId'])}, {s(sc['name'])}, {s(sc['type'])}, {s(sc['gradeLow'])}, "
            f"{s(sc['gradeHigh'])}, {s(sc['zip'])}, {s(sc['districtId'])}, {s(sc['enrollment'])}, "
            f"{s(sc['studentTeacherRatio'])}, ST_SetSRID(ST_Point({sc['lon']}, {sc['lat']}), 4326))"
        )
    lines.append(",\n".join(rows) + "\non conflict (nces_id) do nothing;\n")

    # Safety
    lines.append("insert into school_safety (nces_id, school_year, source, aggravated_assaults, violent_incidents_total, threats_of_violence, theft_larceny, vandalism, drug_incidents, weapons_possession, police_calls, security_cameras, controlled_building_access, sworn_law_enforcement, visitor_sign_in) values")
    rows = []
    for r in safety:
        rows.append(
            f"  ({s(r['ncesId'])}, {s(r['schoolYear'])}, {s(r['source'])}, {s(r['aggravatedAssaults'])}, "
            f"{s(r['violentIncidentsTotal'])}, {s(r['threatsOfViolence'])}, {s(r['theftLarceny'])}, "
            f"{s(r['vandalism'])}, {s(r['drugIncidents'])}, {s(r['weaponsPossession'])}, {s(r['policeCalls'])}, "
            f"{s(r['securityCameras'])}, {s(r['controlledBuildingAccess'])}, {s(r['swornLawEnforcementOnSite'])}, "
            f"{s(r['visitorSignIn'])})"
        )
    lines.append(",\n".join(rows) + "\non conflict (nces_id) do nothing;\n")

    # Graduation
    lines.append("insert into school_graduation (nces_id, school_year, source, grad_rate_4yr, college_going_rate) values")
    rows = []
    for r in graduation:
        rows.append(
            f"  ({s(r['ncesId'])}, {s(r['schoolYear'])}, {s(r['source'])}, {s(r['gradRate4yr'])}, "
            f"{s(r['collegeGoingRate'])})"
        )
    lines.append(",\n".join(rows) + "\non conflict (nces_id) do nothing;\n")

    lines.append("commit;")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
